[package]
name = "kevsh"
version = "0.1.0"
authors = ["Kevin Turner <kevinturner@utexas.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.7"
signal-hook = "0.3.0"